// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWczZsxbvvntc3RLVh3UrjgNNb1ENqXg',
    appId: '1:705193680672:web:25fa79438622a9f58d0145',
    messagingSenderId: '705193680672',
    projectId: 'sprouty-app-7f325',
    authDomain: 'sprouty-app-7f325.firebaseapp.com',
    storageBucket: 'sprouty-app-7f325.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbp0MdxD9VPhF0vBwyUI0FFlk4-89CCaA',
    appId: '1:705193680672:android:18b28c4cbb887c1a8d0145',
    messagingSenderId: '705193680672',
    projectId: 'sprouty-app-7f325',
    storageBucket: 'sprouty-app-7f325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfOQk-sh8HCH_3VrFHKNJ79yMnL1gMZ4',
    appId: '1:705193680672:ios:25fa9503e106f9cf8d0145',
    messagingSenderId: '705193680672',
    projectId: 'sprouty-app-7f325',
    storageBucket: 'sprouty-app-7f325.firebasestorage.app',
    iosBundleId: 'com.example.sproutyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHfOQk-sh8HCH_3VrFHKNJ79yMnL1gMZ4',
    appId: '1:705193680672:ios:25fa9503e106f9cf8d0145',
    messagingSenderId: '705193680672',
    projectId: 'sprouty-app-7f325',
    storageBucket: 'sprouty-app-7f325.firebasestorage.app',
    iosBundleId: 'com.example.sproutyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKWczZsxbvvntc3RLVh3UrjgNNb1ENqXg',
    appId: '1:705193680672:web:fb78647626d8ba198d0145',
    messagingSenderId: '705193680672',
    projectId: 'sprouty-app-7f325',
    authDomain: 'sprouty-app-7f325.firebaseapp.com',
    storageBucket: 'sprouty-app-7f325.firebasestorage.app',
  );
}
