# Generated by Django 5.2.8 on 2025-11-11 20:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comun', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('humedad_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luz_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luz_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'planta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('metodo_login', models.CharField(choices=[('local', 'Local'), ('google', 'Google'), ('facebook', 'Facebook')], default='local', max_length=20)),
                ('foto_perfil', models.URLField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='macetas_api_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='macetas_api_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Maceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maceta', models.CharField(max_length=100)),
                ('ssid_wifi', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_conexion', models.BooleanField(default=False)),
                ('fecha_configuracion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'maceta',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_lectura', models.DateTimeField(auto_now_add=True)),
                ('maceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macetas_api.maceta')),
            ],
            options={
                'db_table': 'lecturasensor',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMaceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luz_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notificar_alertas', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('maceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macetas_api.maceta')),
            ],
            options={
                'db_table': 'configuracionmaceta',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('recordatorio', 'Recordatorio'), ('informacion', 'Información')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('maceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macetas_api.maceta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='JardinVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macetas_api.maceta')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macetas_api.planta')),
            ],
            options={
                'db_table': 'jardinvirtual',
            },
        ),
    ]
