# Generated by Django 5.2.8 on 2025-11-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macetas_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturasensor',
            name='luz',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
