# Generated by Django 6.0 on 2025-12-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macetas_api', '0002_alter_lecturasensor_luz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='username',
        ),
        migrations.AddField(
            model_name='planta',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
