# Generated by Django 6.0 on 2025-12-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macetas_api', '0003_remove_usuario_last_name_remove_usuario_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='imagen',
        ),
    ]
